-- FamilyStream Hub v0.2: additive migration
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS vod_sources (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL, url TEXT, authorized INTEGER DEFAULT 0, approved INTEGER DEFAULT 0, enabled INTEGER DEFAULT 0, config_json TEXT DEFAULT '{}', first_seen TEXT, last_seen TEXT);
CREATE TABLE IF NOT EXISTS vod_categories (id TEXT PRIMARY KEY, name TEXT NOT NULL, parent_id TEXT);
CREATE TABLE IF NOT EXISTS vod_movies (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL, provider_item_id TEXT NOT NULL, title TEXT NOT NULL, original_title TEXT, year INTEGER, plot TEXT, runtime INTEGER, genres TEXT DEFAULT '[]', country TEXT, language TEXT, rating REAL, poster TEXT, backdrop TEXT, tmdb_id TEXT, imdb_id TEXT, stream_status TEXT DEFAULT 'new', rights_status TEXT DEFAULT 'review_required', first_seen TEXT, last_seen TEXT, removed_at TEXT, published INTEGER DEFAULT 0, canonical_id TEXT, UNIQUE(provider_id, provider_item_id));
CREATE TABLE IF NOT EXISTS vod_series (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL, provider_series_id TEXT NOT NULL, title TEXT NOT NULL, original_title TEXT, year INTEGER, plot TEXT, genres TEXT DEFAULT '[]', poster TEXT, backdrop TEXT, tmdb_id TEXT, imdb_id TEXT, status TEXT DEFAULT 'active', rights_status TEXT DEFAULT 'review_required', first_seen TEXT, last_seen TEXT, removed_at TEXT, published INTEGER DEFAULT 0, canonical_id TEXT, UNIQUE(provider_id, provider_series_id));
CREATE TABLE IF NOT EXISTS vod_seasons (id TEXT PRIMARY KEY, series_id TEXT NOT NULL, season_number INTEGER NOT NULL, title TEXT, UNIQUE(series_id, season_number));
CREATE TABLE IF NOT EXISTS vod_episodes (id TEXT PRIMARY KEY, series_id TEXT NOT NULL, season_id TEXT, provider_item_id TEXT, season_number INTEGER, episode_number INTEGER, title TEXT NOT NULL, plot TEXT, air_date TEXT, duration INTEGER, stream_id TEXT, first_seen TEXT, last_seen TEXT, published INTEGER DEFAULT 0, UNIQUE(series_id, season_number, episode_number));
CREATE TABLE IF NOT EXISTS vod_streams (id TEXT PRIMARY KEY, item_type TEXT NOT NULL, item_id TEXT NOT NULL, provider_id TEXT NOT NULL, url TEXT NOT NULL, quality TEXT, headers_json TEXT DEFAULT '{}', status TEXT DEFAULT 'new', score REAL DEFAULT 0, is_primary INTEGER DEFAULT 0, last_checked TEXT, last_success TEXT, failure_count INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS vod_rights (id TEXT PRIMARY KEY, item_type TEXT NOT NULL, item_id TEXT NOT NULL, license TEXT, license_url TEXT, creator TEXT, attribution TEXT, rights_status TEXT DEFAULT 'review_required', evidence_url TEXT, checked_at TEXT);
CREATE TABLE IF NOT EXISTS vod_sync_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id TEXT, started_at TEXT, finished_at TEXT, new_items INTEGER DEFAULT 0, updated_items INTEGER DEFAULT 0, removed_items INTEGER DEFAULT 0, error TEXT);
CREATE TABLE IF NOT EXISTS vod_metadata (item_type TEXT NOT NULL, item_id TEXT NOT NULL, source TEXT NOT NULL, payload_json TEXT NOT NULL, confidence REAL, status TEXT DEFAULT 'matched', updated_at TEXT, PRIMARY KEY(item_type,item_id,source));
CREATE TABLE IF NOT EXISTS source_discovery (id TEXT PRIMARY KEY, name TEXT, url TEXT, type TEXT, provenance TEXT, approved INTEGER DEFAULT 0, enabled INTEGER DEFAULT 0, checked_at TEXT, notes TEXT);
CREATE INDEX IF NOT EXISTS idx_vod_movies_published ON vod_movies(published, last_seen);
CREATE INDEX IF NOT EXISTS idx_vod_series_published ON vod_series(published, last_seen);
CREATE INDEX IF NOT EXISTS idx_vod_streams_item ON vod_streams(item_type, item_id, is_primary);
